services:
  billigtanken:
    build: .
    container_name: billigtanken
    restart: unless-stopped
    volumes:
      - logs:/var/log
    networks:
      - default
      - reverse-proxy

volumes:
  logs:

networks:
  reverse-proxy:
    external: true
